steps:
  - name: "ghcr.io/astral-sh/uv:python3.12-alpine"
    script: uv export --no-emit-project -o requirements.txt
    id: "export-requirements"

  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    id: "deploy-discover"
    script: >
      gcloud functions deploy discover
      --gen2
      --runtime=python312
      --region=${_REGION}
      --source=.
      --entry-point=discover
      --timeout=540s
      --trigger-http --allow-unauthenticated
      --set-env-vars=BUCKET=${_BUCKET},PROCESSOR_TOPIC=${_PROCESSOR_TOPIC}
    waitFor:
      - "export-requirements"

  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    id: "deploy-processor"
    script: >
      gcloud functions deploy processor
      --gen2
      --runtime=python312
      --region=${_REGION}
      --source=.
      --entry-point=processor
      --timeout=540s
      --memory=512MiB
      --trigger-topic=${_PROCESSOR_TOPIC}
    waitFor:
      - "export-requirements"

  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    id: "deploy-aggregator"
    script: >
      gcloud functions deploy aggregator
      --gen2
      --runtime=python312
      --region=${_FIRESTORE_REGION}
      --trigger-location=${_FIRESTORE_REGION}
      --source=.
      --entry-point=aggregator
      --set-env-vars=PREPARE_DATA_TOPIC=${_PREPARE_DATA_TOPIC}
      --trigger-event-filters=type="google.cloud.firestore.document.v1.updated"
      --trigger-event-filters=database="(default)"
      --trigger-event-filters-path-pattern="document=batches/{batchId}"
    waitFor:
      - "export-requirements"

  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    id: "deploy-prepare-data"
    script: >
      gcloud functions deploy prepare_data
      --gen2
      --runtime=python312
      --region=${_REGION}
      --source=.
      --entry-point=prepare_data
      --timeout=540s
      --memory=512MiB
      --set-env-vars=REBUILD_SITE_TOPIC=videoclub-rebuild-site
      --trigger-topic=${_PREPARE_DATA_TOPIC}
    waitFor:
      - "export-requirements"


# Manual Cloud Scheduler setup documented in docs/extractor-pipeline.md

substitutions:
  _REGION: europe-west9
  _PROCESSOR_TOPIC: videoclub-processor
  _BUCKET: videoclub-test
  _FIRESTORE_REGION: europe-west9
  _PREPARE_DATA_TOPIC: videoclub-prepare-data

options:
  automapSubstitutions: true
