steps:
  - name: "ghcr.io/astral-sh/uv:python3.12-alpine"
    script: uv export --no-dev --no-emit-project -o requirements.txt
    id: "export-requirements"
  
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    script: >
      gcloud functions deploy
      download-video --entry-point=download
      ${_FUNCTIONS_DEPLOY_BASE_ARGS}
    waitFor:
      - "export-requirements"

  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    script: >
      gcloud functions deploy
      annotate-video --entry-point=annotate
      ${_FUNCTIONS_DEPLOY_BASE_ARGS}
    waitFor:
      - "export-requirements"
  
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    script: >
      gcloud functions deploy
      process-video-annotations --entry-point=process_video_annotations
      --memory=512MiB
      ${_FUNCTIONS_DEPLOY_BASE_ARGS}
    waitFor:
      - "export-requirements"

options:
  automapSubstitutions: true

substitutions:
  _FUNCTIONS_DEPLOY_BASE_ARGS: >
    --source=.
    --runtime=python312
    --gen2
    --region=europe-west9
    --trigger-http
    --allow-unauthenticated