steps:
  - id: prepare-data
    name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: bash
    dir: web
    env:
      - DEFAULT_DATA_BUCKET=${_DATA_BUCKET}
      - FUNCTION_REGION=${_FUNCTION_REGION}
      - GCP_PROJECT=${_GCP_PROJECT}
    args: ["-c", "set -euo pipefail && python3 scripts/invoke_prepare_data.py"]
  - id: install
    name: node:22
    entrypoint: bash
    dir: web
    args:
      - -c
      - |
          set -euo pipefail
          npm install -g pnpm@10.12.4 --force
          pnpm install --frozen-lockfile
  - id: build
    name: node:22
    entrypoint: bash
    dir: web
    args:
      - -c
      - |
          set -euo pipefail
          npm install -g pnpm@10.12.4 --force
          pnpm build
  - id: deploy-hosting
    name: us-docker.pkg.dev/firebase-cli/us/firebase
    entrypoint: firebase
    dir: web
    args: ["deploy", "--project=${_FIREBASE_PROJECT_ID}", "--only=hosting"]
substitutions:
  _FIREBASE_PROJECT_ID: videoclub-staging
  _DATA_BUCKET: videoclub-test
  _GCP_PROJECT: videoclub-447210
  _FUNCTION_REGION: europe-west9
options:
  logging: CLOUD_LOGGING_ONLY
